version: '3'
services:
  app-server:
    build:
      context: ./app-server
      dockerfile: Dockerfile
    container_name: app-server
    ports:
      - 1234:3000
    networks:
      - app-network
    environment:
      - MONGO_DB_USERNAME=root
      - MONGO_DB_PWD=password

  web-server:
    build:
      context: ./web-server
      dockerfile: Dockerfile
    container_name: web-server
    ports:
      - 1235:80
    networks:
      - app-network

  mongo:
    image: mongo
    container_name: mongo
    ports:
      - 1236:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password
    networks:
      - app-network      
    volumes:
      - app-volume:/data/db

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    ports:
      - 1237:8081
    networks:
      - app-network
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
      - ME_CONFIG_MONGODB_SERVER=mongo

volumes:
  app-volume:
    driver: local

networks:
  app-network:
    driver: bridge
