apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-server
  template:
    metadata:
      labels:
        app: app-server
    spec:
      containers:
      - name: app-server
        image: wazeazure/app-server:latest # Build and push your app-server image to a registry like Docker Hub
        env:
        - name: MONGO_DB_USERNAME
          value: "root"
        - name: MONGO_DB_PWD
          value: "password"
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: app-server
spec:
  type: NodePort
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30000
  selector:
    app: app-server
