CREATE DATABASE IF NOT EXISTS edbertdb;
USE edbertdb;

-- Buat pengguna untuk replikasi
CREATE USER 'master1'@'%' IDENTIFIED BY 'master1';
GRANT REPLICATION SLAVE ON *.* TO 'master1'@'%';
FLUSH PRIVILEGES;

CHANGE MASTER TO MASTER_HOST='mariadb2', MASTER_USER='master2', MASTER_PASSWORD='master2', MASTER_PORT=3306, MASTER_LOG_FILE='mysql-bin.000001', MASTER_LOG_POS=4;
START SLAVE;